- name: Install apt packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - bc
      - bzip2
      - ca-certificates
      - curl
      - dstat
      - emacs
      - ffmpeg
      - git
      - gnupg
      - gnupg2
      - htop
      - iotop
      - iproute2
      - iputils-ping
      - iverilog
      - jq
      - language-pack-ja
      - less
      - locales
      - lsb-core
      - lv
      - neovim
      - net-tools
      - nis
      - openssh-client
      - openssh-server
      - openssl
      - pass
      - peco
      - pigz
      - pocl-opencl-icd
      - python3
      - python3-dev
      - python3-minimal
      - python3-pip
      - python3-venv
      - rpm
      - ruby
      - socat
      - software-properties-common
      - sudo
      - sysstat
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - xz-utils
      - zsh
      - zstd
    state: present

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo

- name: Ensure a locale exists
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: Ensure a locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set locale
  command: update-locale LANG=ja_JP.UTF-8

- name: Select Python 3.10 as /usr/bin/python
  community.general.alternatives:
    name: python
    path: /usr/bin/python3.10
    link: /usr/bin/python

#- name: Select Python 3.8 as /usr/bin/python3
#  community.general.alternatives:
#    name: python
#    path: /usr/bin/python3.8
#    link: /usr/bin/python3

- name: Install pip packages
  ansible.builtin.pip:
    name:
     - Flask
     - jupyter
     - jupyterlab
     - matplotlib
     - numpy
     - pillow
     - pipenv
     - pynq
     - pyopencl
     - pyserial
     - scipy
     - setuptools
     - wheel
