#! /bin/sh

test x"$SHELL" = x"" && SHELL=/bin/bash
test x"$1"     = x"" && set -- default

vncconfig -iconic &
$SHELL -l <<EOF
export XDG_SESSION_TYPE=x11
exec /etc/X11/Xsession "$@"
EOF
vncserver -kill $DISPLAY
